theme: jekyll-theme-minimal
title: Unum.xyz
description: Artificial Intelligence, but scalable!

navbar-links:
  Founder: "http://ashvardanian.com"
  Projects:
    - Semantic: "http://unum.xyz/semantic/"
    - Fast: "http://unum.xyz/fast/"

avatar: "unum.png"
title-img: "unum.png"

author:
  name: Ashot Vardanian

social-network-links:
  email: "a@unum.xyz"
  facebook: ashvardanian
  github: ashvardanian
  twitter: ashvardanian
  reddit: ashvardanian
  linkedin: ashvardanian
  stackoverflow: "2766161/ashot-vardanian"
  instagram: ashvardanian
  youtube: user/ashvardanian
  yelp: ashvardanian
  
share-links-active:
  twitter: true
  facebook: true
  linkedin: true

url-pretty: "unum.xyz"
#google_analytics: ""

exclude:
  - CHANGELOG.md
  - CNAME
  - Dockerfile
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - Vagrantfile
  
