title: Unum
email: info@unum.am
description: A research-heavy software company focused on High Performance Computing, Artificial Intelligence and their applications
baseurl: "" # the subpath of your site, e.g. /blog
url: https://unum.am
twitter_username: unum_am
github_username:  unumam
logo: "/apple-icon.png"

# Build settings
# https://github.com/pmarsceill/just-the-docs/issues/297
# theme: just-the-docs
remote_theme: pmarsceill/just-the-docs
plugins:
  - jekyll-feed
  - jekyll-analytics

ga_tracking: UA-150644745-1
ga_tracking_anonymize_ip: false

# Exclude from processing.
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - build.sh
  - CHANGELOG.md
  - CNAME
  - Dockerfile
  - LICENSE
  - README.md
  - Vagrantfile
  
