title: Unum
email: info@unum.am
description: >- # this means to ignore newlines until "baseurl:"
  A research-heavy software company focused on High Performance Computing, Artificial Intelligence and their applications
baseurl: "" # the subpath of your site, e.g. /blog
url: https://unum.am
twitter_username: unum_am
github_username:  unumam
google_analytics: UA-150644745-1

# Build settings
# https://github.com/pmarsceill/just-the-docs/issues/297
# theme: just-the-docs
remote_theme: pmarsceill/just-the-docs
plugins:
  - jekyll-feed

# Exclude from processing.
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - build.sh
  - CHANGELOG.md
  - CNAME
  - Dockerfile
  - LICENSE
  - README.md
  - Vagrantfile
  
