theme: minima
title: Unum.xyz
description: Artificial Intelligence, but scalable!

header_pages:
  - about.md
  - portfolio.md

favicon: "unum.png"
avatar: "unum.png"
title-img: "unum.png"

author:
  name: Ashot Vardanian

minima:
  social_links:
    email: "a@unum.xyz"
    facebook: ashvardanian
    github: ashvardanian
    twitter: ashvardanian
    reddit: ashvardanian
    linkedin: ashvardanian
    stackoverflow: "2766161/ashot-vardanian"
    instagram: ashvardanian
    youtube: user/ashvardanian
    yelp: ashvardanian
  
share-links-active:
  twitter: true
  facebook: true
  linkedin: true

url-pretty: "unum.xyz"
google_analytics: "UA-150644745-1"

exclude:
  - CHANGELOG.md
  - CNAME
  - Dockerfile
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - Vagrantfile
  
